export default [
  {question: "What is the capital of France?", answer: "Paris"},
  {question: "What is the largest continent?", answer: "Asia"},
  {question: "What is the currency of Japan?", answer: "Yen"},
  {question: "Which planet is known as the Red Planet?", answer: "Mars"},
  {question: "What is the tallest animal in the world?", answer: "Giraffe"},
  {question: "Which planet is known as the Blue Planet?", answer: "Earth"},
  {question: "What is the longest river in the world?", answer: "Nile"},
  {question: "What is the currency of the United Kingdom?", answer: "Pound"},
  {question: "Which animal is known as the King of the Jungle?", answer: "Lion"},
  {question: "What is the national flower of France?", answer: "Lily"},
  {question: "What is the capital of France?", answer: "Paris" },
  {question: "What is the largest planet in our solar system?", answer: "Jupiter" },
  {question: "What color is a banana?", answer: "Yellow" },
  {question: "What is the seventh month of the year?", answer: "July" },
  {question: "What is the opposite of 'hot'?", answer: "Cold" },
  {question: "What is the capital of Australia?", answer: "Canberra" },
  {question: "What is the largest ocean in the world?", answer: "Pacific" },
  {question: "What do bees produce?", answer: "Honey" },
  {question: "What is the color of grass?", answer: "Green" },
  {question: "What is the tallest animal?", answer: "Giraffe" },
  {question: "What is the opposite of 'day'?", answer: "Night" },
  {question: "What is the currency of the United States?", answer: "Dollar" },
  {question: "What is the capital of England?", answer: "London" },
  {question: "What is the main ingredient in bread?", answer: "Flour" },
  {question: "What is the opposite of 'big'?", answer: "Small" },
  {question: "What is the animal symbol of China?", answer: "Panda" },
  {question: "What is the capital of Brazil?", answer: "Brasilia" },
  {question: "What is the largest bird in the world?", answer: "Ostrich" },
  {question: "What is the main language spoken in Japan?", answer: "Japanese" },
  {question: "What is the opposite of 'fast'?", answer: "Slow" },
  {question: "What is the capital of Canada?", answer: "Ottawa" },
] 